### ISSUE TITLE
Checksum mismatch for liberica-jdk17-full

### ISSUE THREAD

**Issue by Nepherte** [bell-sw/homebrew-liberica#47]
Homebrew reports a checksum mismatch when installing liberica-jdk17-full. What's even more odd is that the reported sha1 checksum on the liberica website also does not correspond with the pkg you can download from the website.

`
==> Upgrading liberica-jdk17-full
==> Downloading https://download.bell-sw.com/java/17.0.6%2B10/bellsoft-jdk17.0.6%2B10-macos-aarch64-full.pkg
Already downloaded: /Users/bart/Library/Caches/Homebrew/downloads/fba328291161de8ea96e750ef756fc2045e4f1d2129b2962416fef251d74fac0--bellsoft-jdk17.0.6+10-macos-aarch64-full.pkg
==> Purging files for version 17.0.6,10 of Cask liberica-jdk17-full
Error: bell-sw/liberica/liberica-jdk17-full: SHA256 mismatch
Expected: cab189fb18bca7e7a39babe717d0a54bdb5c500be488b3d28e53656c94e823e1
  Actual: f931444f2d0fee79be7bed473fa64273f8e60c9f391a1e92a7fd4c687fc7f0d2`

**Comment by jshiell** [comment]
I'm seeing this for `liberica-jdk17` as well:

```
==> Upgrading 1 outdated package:
bell-sw/liberica/liberica-jdk17 17.0.5,8 -> 17.0.6,10
==> Upgrading liberica-jdk17
==> Downloading https://download.bell-sw.com/java/17.0.6%2B10/bellsoft-jdk17.0.6%2B10-macos-aarch64.pkg
######################################################################## 100.0%
==> Purging files for version 17.0.6,10 of Cask liberica-jdk17
Error: bell-sw/liberica/liberica-jdk17: SHA256 mismatch
Expected: 41dbfd289f5f1c3297964ad527b6fcef385544b71b55ce437bf135266f33c1cb
  Actual: 9bd7b04baa4be476e389b6963a1c8bf206989c4e143876ba9145a2b0abc6872a
    File: /Users/someone/Library/Caches/Homebrew/downloads/e190599836656f538eb7d3c553af5afe889bbc02072af567db89fea7f7c1bacb--bellsoft-jdk17.0.6+10-macos-aarch64.pkg
To retry an incomplete download, remove the file above.
```

**Comment by PakhomGolynga** [comment]
Hi, thanks for catching this!
We have updated repository, this is now consistent.
