### ISSUE TITLE
Incorrect sha256 hash in liberica-jdk8-full for 1.8.0,242 version

### ISSUE THREAD

**Issue by dinix2008** [bell-sw/homebrew-liberica#6]
==> Verifying SHA-256 checksum for Cask 'liberica-jdk8-full'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'liberica-jdk8-full' does not match.
Expected: 2037e03ad361a8ff36e8edd8ca1f2d9ec8d8572b41a2e53f06bf0291b1b972d7
  Actual: 771f3671d7b26c2ecda1287f5cb9fb9209e72185a6c20a7ac1a94798e1c2c15d

**Comment by bell-sw** [comment]
Thanks for reporting.
The issue is fixed.
